# Используем образ с Delve (отладчик для Go)
FROM golang:1.23-alpine

WORKDIR /app

# Устанавливаем Delve и зависимости
RUN apk add --no-cache git
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Копируем зависимости и собираем
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Запускаем приложение в режиме отладки
CMD ["dlv", "debug", "--headless", "--listen=:40000", "--api-version=2", "--accept-multiclient", "--continue", "./cmd"]